apiVersion: v1
kind: ReplicationController
metadata:
  name: replica01
  labels:
    env: production
spec:
  replicas: 3
  selector:
    env: production
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
       - name: webserver
         image: nginx
         ports:
          - containerPort: 80
