apiVersion: apps/v1
kind: Deployment
metadata:
  name : xyz
spec:
  selector:
     matchLabels:
       app: xyz
  replicas: 3
  template:
    metadata:
       labels:
         app: xyz
    spec:
      containers:
      - name: xyz       
        image: nginx:1.14.2
        ports:
         - containerPort: 80
                
