apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
       - name: nginx-container
         image: nginx
         ports:
          - containerPort: 80

