apiVersion: v1
kind: Pod
metadata:
  name : twocontainerpod
  labels: 
    env: production
spec:
  containers:
   - name: aplinecontainer
     image: hshar/webapp
     ports:
      - containerPort: 9876
   - name: c2
     image: centos:7
     command:
       - "bin/bash"
       - "-c"
       - "sleep 10000"
