apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01
  labels:
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
       - name: web-conatiner
         image: nginx
         ports:
          - containerPort: 8

